1、关于ES6 Proxy (2019 今日头条)

2、你觉得TypeScript 和 JavaScript有什么区别

- 语言层面
 - Javascript 和 TypeScript 都是ECMAScript 的具体实现
 - TypeScript 是静态类型，而JavaScript 是动态类型
 - TypeScript 扩展了JavaScript 并且完全包容javascript
执行方面
- TS 需要编译
- JS 不需要编译
厂商层面
- Javascript 由Netscape 率先



TypeScript中的 type 和 instance 区别
```js
interface User {
  name: string,
  age: number
}

insterface SetUser {
  (name: string, age: number) : void;
}


type SetUser = (name: string, age: number) => void;

// 都允许扩展


// interface extends type

type Name = {
  name: string;
}

instance
```

- 不同点
```js
// type 不是一个类型，它是类型别名
 // type 可以声明基本类型别名，联合类型，元祖等类型
 // 基本类型别名
 type Name = string


// interface 可以 而type不行

// interface 能够声明合并
interface User {
  name: string,
  age: number
}
interface User {
  sex: string
}

new Error 不会终止成员运行
```

### async / await 如果右边的方法执行出错了该怎么办 （百度一面2020)
- 方式一 使用Promise 的catch 方法捕获异常 不完善
- 方式二 在async 函数中使用try -catch 捕获异常 （推荐）
```js
async function f() {
  console.log(1)
  await new Promise((resolve, reject) => {
    console.log(2)
    throw new Error('出错了')
  }).catch(err => {
    console.log(3)
    console.log('执行失败了')
  })
  console.log(4)
}
// 1234
```
使用 try-catch 的时候，会把容易引发异常的代码写到try 里面
```js
async function f() {
  try {
    // await new Promise((resolve, reject) => {
    //   // throw new Error('出错了')
    //   resolve()
    // })
    await new Promise((resolve, reject) => {
      throw new Error('出错了')
    })
    
    console.log('正常输出')
  } catch (err) {
    // 这里用来捕获异常
    console.log('异常了)
  }
}
```

```js
async function Login () {
  // 接口请求异常， 
  // 用户名错误、密码错误、用户不存在、500
  // 前提条件： 接口把所有的异常都通过HTTp状态吗来返回
  // 尤其是在使用axios 请求库的时候， 它会把所有超出200- 300范围的状态码捕获
  try {
     catch (err) {

     }
  }
}
```

注意
- try-catch 只能捕获同步异常
- 还有async 中的await Promise异常
- try-catch 不能直接捕获Promise 调用异常

```js
try {
  const p = new Promise((resolve, reject) => {
    throw new Error('error')
    fs.readFile('./login.js', (err, data) => {
      if (err) {
        reject(err)
      } else {
        resolve(data)
      }
    })
  })
  // 这样可以捕获到
  // p.then(data => {
  //   console.log(data)
  // }).catch (err => {
  //   console.log('手动 调用catch 捕获异常')
  // })
} catch (err) {
  console.log('失败了')
}

// 没有错误
```
 